name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Enable PNPM
        run: corepack enable
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Install Playwright (Firefox)
        run: npx playwright install --with-deps firefox
      - name: E2E (headless Firefox)
        env:
          BASE_URL: http://localhost:3000
        run: |
          pnpm start & npx wait-on http://localhost:3000
          pnpm test:e2e