name: e2e-windows (noweb)

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  e2e-win-noweb:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Firefox only)
        run: npx playwright install --with-deps

      - name: Build Next app
        run: npm run build

      - name: Start server on :3003 (background)
        shell: pwsh
        run: |
          Start-Process -NoNewWindow -FilePath "powershell" -ArgumentList "-NoLogo","-NoProfile","-Command","npm run start" | Out-Null

      - name: Wait for /api/healthz
        shell: pwsh
        run: |
          $deadline = (Get-Date).AddSeconds(120)
          do {
            Start-Sleep -Milliseconds 500
            try {
              iwr http://localhost:3003/api/healthz -UseBasicParsing -TimeoutSec 2 | Out-Null
              $ok = $true
            } catch { $ok = $false }
          } until ($ok -or (Get-Date) -gt $deadline)
          if (-not $ok) { throw "Server not ready on :3003" }

      - name: Run e2e (no-web config, Firefox)
        env:
          CI: 'true'
        run: npx playwright test --config=playwright/playwright.noweb.config.ts --project=firefox

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-windows
          path: playwright-report
          retention-days: 10

      - name: Upload traces/videos (failures)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-windows
          path: |
            test-results
            playwright-report/*.zip
            playwright-report/data
          retention-days: 10

      - name: Summarize results (top failing specs)
        if: always()
        shell: pwsh
        run: |
          $f = "playwright-report/results.json"
          if (-Not (Test-Path $f)) { "No results.json found" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append; exit 0 }
          $json = Get-Content $f -Raw | ConvertFrom-Json
          $stats = $json?.stats
          $suites = $json?.suites
          $failures = @()
          foreach ($s in $suites) {
            foreach ($spec in $s.specs) {
              foreach ($t in $spec.tests) {
                foreach ($r in $t.results) {
                  if ($r.status -eq "failed") {
                    $failures += [pscustomobject]@{
                      title = $spec.title
                      file = $spec.file
                    }
                    break
                  }
                }
              }
            }
          }
          $summary = @()
          $summary += "# Playwright Summary"
          if ($stats) {
            $summary += ""
            $summary += "**Passed:** $($stats.expected)  **Failed:** $($stats.unexpected)  **Flaky:** $($stats.flaky)  **Skipped:** $($stats.skipped)"
          }
          if ($failures.Count -gt 0) {
            $summary += ""
            $summary += "## Failing specs"
            $failures | Select-Object -Unique file, title | ForEach-Object {
              $summary += "- `$($_.file)` → **$($_.title)**"
            }
          } else {
            $summary += ""
            $summary += "All specs passed ✅"
          }
          $summary -join "`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
